// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Practikap.Infrastructure.Persistence;

#nullable disable

namespace Practikap.Infrastructure.Migrations
{
    [DbContext(typeof(PractikapDbContext))]
    [Migration("20260829123644_MonitoriaSinEmpresa")]
    partial class MonitoriaSinEmpresa
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Practikap.Domain.Entities.CalificacionAprendiz", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<bool>("Anulado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("anulado");

                    b.Property<uint?>("AnuladoPor")
                        .HasColumnType("int unsigned")
                        .HasColumnName("anulado_por");

                    b.Property<string>("Comentario")
                        .HasColumnType("text")
                        .HasColumnName("comentario");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_registro")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<uint>("PracticaId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("practica_id");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(3,1)")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("AnuladoPor")
                        .HasDatabaseName("idx_calificaciones_aprendiz_anulado_por");

                    b.HasIndex("PracticaId")
                        .HasDatabaseName("idx_calificaciones_aprendiz_practica");

                    b.ToTable("calificaciones_aprendiz", null, t =>
                        {
                            t.HasCheckConstraint("chk_calificaciones_aprendiz_valor", "valor >= 0.0 AND valor <= 5.0");
                        });
                });

            modelBuilder.Entity("Practikap.Domain.Entities.CalificacionInstructor", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<bool>("Anulado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("anulado");

                    b.Property<uint?>("AnuladoPor")
                        .HasColumnType("int unsigned")
                        .HasColumnName("anulado_por");

                    b.Property<string>("Comentario")
                        .HasColumnType("text")
                        .HasColumnName("comentario");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_registro")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<uint>("PracticaId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("practica_id");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(3,1)")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("AnuladoPor")
                        .HasDatabaseName("idx_calificaciones_instructor_anulado_por");

                    b.HasIndex("PracticaId")
                        .HasDatabaseName("idx_calificaciones_instructor_practica");

                    b.ToTable("calificaciones_instructor", null, t =>
                        {
                            t.HasCheckConstraint("chk_calificaciones_instructor_valor", "valor >= 0.0 AND valor <= 5.0");
                        });
                });

            modelBuilder.Entity("Practikap.Domain.Entities.Configuracion", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<uint>("ActualizadoPor")
                        .HasColumnType("int unsigned")
                        .HasColumnName("actualizado_por");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("clave");

                    b.Property<string>("Descripcion")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descripcion");

                    b.Property<DateTime>("FechaActualizacion")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_actualizacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("FechaActualizacion"));

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("ActualizadoPor")
                        .HasDatabaseName("idx_configuracion_actualizado_por");

                    b.HasIndex("Clave")
                        .IsUnique()
                        .HasDatabaseName("uq_configuracion_clave");

                    b.ToTable("configuracion", (string)null);
                });

            modelBuilder.Entity("Practikap.Domain.Entities.Empresa", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<string>("JefeInmediatoCorreo")
                        .HasColumnType("varchar(180)")
                        .HasColumnName("jefe_inmediato_correo");

                    b.Property<string>("JefeInmediatoNombre")
                        .HasColumnType("varchar(150)")
                        .HasColumnName("jefe_inmediato_nombre");

                    b.Property<string>("JefeInmediatoTelefono")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("jefe_inmediato_telefono");

                    b.Property<string>("Nit")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("nit");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("razon_social");

                    b.HasKey("Id");

                    b.HasIndex("Nit")
                        .IsUnique()
                        .HasDatabaseName("uq_empresas_nit");

                    b.ToTable("empresas", (string)null);
                });

            modelBuilder.Entity("Practikap.Domain.Entities.Ficha", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<string>("NumeroFicha")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("numero_ficha");

                    b.Property<uint>("ProgramaId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("programa_id");

                    b.HasKey("Id");

                    b.HasIndex("NumeroFicha")
                        .IsUnique()
                        .HasDatabaseName("uq_fichas_numero");

                    b.HasIndex("ProgramaId")
                        .HasDatabaseName("idx_fichas_programa");

                    b.ToTable("fichas", (string)null);
                });

            modelBuilder.Entity("Practikap.Domain.Entities.Mensaje", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contenido");

                    b.Property<uint>("EmisorId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("emisor_id");

                    b.Property<DateTime>("FechaEnvio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_envio")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("Leido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("leido");

                    b.Property<uint>("PracticaId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("practica_id");

                    b.Property<uint>("ReceptorId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("receptor_id");

                    b.HasKey("Id");

                    b.HasIndex("EmisorId")
                        .HasDatabaseName("idx_mensajes_emisor");

                    b.HasIndex("PracticaId")
                        .HasDatabaseName("idx_mensajes_practica");

                    b.HasIndex("ReceptorId")
                        .HasDatabaseName("idx_mensajes_receptor");

                    b.ToTable("mensajes", (string)null);
                });

            modelBuilder.Entity("Practikap.Domain.Entities.Notificacion", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("contenido");

                    b.Property<DateTime>("FechaGeneracion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_generacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("Leida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("leida");

                    b.Property<uint?>("ReglaId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("regla_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("enum('Calificacion','Mensaje','Observacion','Riesgo')")
                        .HasColumnName("tipo");

                    b.Property<uint>("UsuarioId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("ReglaId")
                        .HasDatabaseName("idx_notificaciones_regla");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("idx_notificaciones_usuario");

                    b.ToTable("notificaciones", (string)null);
                });

            modelBuilder.Entity("Practikap.Domain.Entities.Observacion", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<bool>("Anulado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("anulado");

                    b.Property<uint?>("AnuladoPor")
                        .HasColumnType("int unsigned")
                        .HasColumnName("anulado_por");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contenido");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_registro")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<uint>("SeguimientoId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("seguimiento_id");

                    b.HasKey("Id");

                    b.HasIndex("AnuladoPor")
                        .HasDatabaseName("idx_observaciones_anulado_por");

                    b.HasIndex("SeguimientoId")
                        .HasDatabaseName("idx_observaciones_seguimiento");

                    b.ToTable("observaciones", (string)null);
                });

            modelBuilder.Entity("Practikap.Domain.Entities.Practica", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<uint>("AprendizId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("aprendiz_id");

                    b.Property<uint?>("EmpresaId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('Pendiente','En curso','Finalizada','En riesgo')")
                        .HasDefaultValue("Pendiente")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateOnly?>("FechaFin")
                        .HasColumnType("date")
                        .HasColumnName("fecha_fin");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date")
                        .HasColumnName("fecha_inicio");

                    b.Property<uint>("FichaId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("ficha_id");

                    b.Property<uint>("InstructorId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("instructor_id");

                    b.Property<string>("Modalidad")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('Contrato de aprendizaje','Pasantía','Proyecto productivo','Monitoría')")
                        .HasDefaultValue("Contrato de aprendizaje")
                        .HasColumnName("modalidad");

                    b.HasKey("Id");

                    b.HasIndex("AprendizId")
                        .HasDatabaseName("idx_practicas_aprendiz");

                    b.HasIndex("EmpresaId")
                        .HasDatabaseName("idx_practicas_empresa");

                    b.HasIndex("Estado")
                        .HasDatabaseName("idx_practicas_estado");

                    b.HasIndex("FichaId")
                        .HasDatabaseName("idx_practicas_ficha");

                    b.HasIndex("InstructorId")
                        .HasDatabaseName("idx_practicas_instructor");

                    b.ToTable("practicas", null, t =>
                        {
                            t.HasCheckConstraint("chk_practicas_empresa_modalidad", "(modalidad IN ('Proyecto productivo','Monitoría') AND empresa_id IS NULL) OR (modalidad NOT IN ('Proyecto productivo','Monitoría') AND empresa_id IS NOT NULL)");

                            t.HasCheckConstraint("chk_practicas_fechas", "fecha_fin IS NULL OR fecha_fin >= fecha_inicio");
                        });
                });

            modelBuilder.Entity("Practikap.Domain.Entities.Programa", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("uq_programas_nombre");

                    b.ToTable("programas", (string)null);
                });

            modelBuilder.Entity("Practikap.Domain.Entities.RegistroAuditoria", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("enum('Anulacion','Retroceso_estado','Cambio_rol','Reasignacion','Configuracion_regla','Otro')")
                        .HasColumnName("accion");

                    b.Property<string>("Detalle")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("detalle");

                    b.Property<string>("EntidadAfectada")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("entidad_afectada");

                    b.Property<uint>("EntidadId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("entidad_id");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_registro")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<uint>("UsuarioId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("idx_auditoria_usuario");

                    b.HasIndex("EntidadAfectada", "EntidadId")
                        .HasDatabaseName("idx_auditoria_entidad");

                    b.ToTable("auditoria", (string)null);
                });

            modelBuilder.Entity("Practikap.Domain.Entities.Regla", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<string>("AccionResultante")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("accion_resultante");

                    b.Property<bool>("Activa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("activa");

                    b.Property<string>("CampoEvaluado")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("campo_evaluado");

                    b.Property<uint>("CreadoPor")
                        .HasColumnType("int unsigned")
                        .HasColumnName("creado_por");

                    b.Property<DateTime>("FechaActualizacion")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_actualizacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("FechaActualizacion"));

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nombre");

                    b.Property<string>("Operador")
                        .IsRequired()
                        .HasColumnType("enum('>','>=','<','<=','=','!=')")
                        .HasColumnName("operador");

                    b.Property<uint>("Prioridad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("prioridad");

                    b.Property<decimal>("Umbral")
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("umbral");

                    b.Property<decimal>("ValorCondicion")
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("valor_condicion");

                    b.HasKey("Id");

                    b.HasIndex("CreadoPor")
                        .HasDatabaseName("idx_reglas_creado_por");

                    b.HasIndex("Activa", "Prioridad")
                        .HasDatabaseName("idx_reglas_activa_prioridad");

                    b.ToTable("reglas", (string)null);
                });

            modelBuilder.Entity("Practikap.Domain.Entities.Reporte", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<DateTime>("FechaGeneracion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_generacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Filtros")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("filtros");

                    b.Property<uint>("GeneradoPor")
                        .HasColumnType("int unsigned")
                        .HasColumnName("generado_por");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("enum('Individual','Grupal')")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("GeneradoPor")
                        .HasDatabaseName("idx_reportes_generador");

                    b.ToTable("reportes", (string)null);
                });

            modelBuilder.Entity("Practikap.Domain.Entities.Rol", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("uq_roles_nombre");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1u,
                            Descripcion = "Gobierna la plataforma, configura el Motor de Reglas y genera reportes globales.",
                            Nombre = "Administrador"
                        },
                        new
                        {
                            Id = 2u,
                            Descripcion = "Responsable pedagógico: asigna aprendices, registra seguimiento y califica.",
                            Nombre = "Instructor"
                        },
                        new
                        {
                            Id = 3u,
                            Descripcion = "Realiza la práctica: consulta su seguimiento y evalua al instructor.",
                            Nombre = "Aprendiz"
                        });
                });

            modelBuilder.Entity("Practikap.Domain.Entities.Seguimiento", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<bool>("Anulado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("anulado");

                    b.Property<uint?>("AnuladoPor")
                        .HasColumnType("int unsigned")
                        .HasColumnName("anulado_por");

                    b.Property<string>("Avance")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("avance");

                    b.Property<string>("Etapa")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("etapa");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_registro")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<uint>("PracticaId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("practica_id");

                    b.HasKey("Id");

                    b.HasIndex("AnuladoPor")
                        .HasDatabaseName("idx_seguimientos_anulado_por");

                    b.HasIndex("PracticaId")
                        .HasDatabaseName("idx_seguimientos_practica");

                    b.ToTable("seguimientos", (string)null);
                });

            modelBuilder.Entity("Practikap.Domain.Entities.TokenRevocado", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<DateTime>("FechaRevocacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_revocacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("enum('Logout','Cambio de contraseña')")
                        .HasColumnName("motivo");

                    b.Property<string>("ReferenciaToken")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("referencia_token");

                    b.Property<uint>("UsuarioId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("ReferenciaToken")
                        .IsUnique()
                        .HasDatabaseName("uq_tokens_revocados_referencia");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("idx_tokens_revocados_usuario");

                    b.ToTable("tokens_revocados", (string)null);
                });

            modelBuilder.Entity("Practikap.Domain.Entities.Usuario", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("apellido");

                    b.Property<string>("ContrasenaHash")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("contrasena_hash");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("varchar(180)")
                        .HasColumnName("correo");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('Activo','Inactivo')")
                        .HasDefaultValue("Activo")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaActualizacion")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_actualizacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("FechaActualizacion"));

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nombre");

                    b.Property<uint>("RolId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("rol_id");

                    b.Property<string>("Telefono")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telefono");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique()
                        .HasDatabaseName("uq_usuarios_correo");

                    b.HasIndex("RolId")
                        .HasDatabaseName("idx_usuarios_rol");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("reporte_practica", b =>
                {
                    b.Property<uint>("reporte_id")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("practica_id")
                        .HasColumnType("int unsigned");

                    b.HasKey("reporte_id", "practica_id");

                    b.HasIndex("practica_id")
                        .HasDatabaseName("idx_reporte_practica_practica");

                    b.ToTable("reporte_practica", (string)null);
                });

            modelBuilder.Entity("Practikap.Domain.Entities.CalificacionAprendiz", b =>
                {
                    b.HasOne("Practikap.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("AnuladoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_calificaciones_aprendiz_anulador");

                    b.HasOne("Practikap.Domain.Entities.Practica", "Practica")
                        .WithMany()
                        .HasForeignKey("PracticaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_calificaciones_aprendiz_practica");

                    b.Navigation("Practica");
                });

            modelBuilder.Entity("Practikap.Domain.Entities.CalificacionInstructor", b =>
                {
                    b.HasOne("Practikap.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("AnuladoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_calificaciones_instructor_anulador");

                    b.HasOne("Practikap.Domain.Entities.Practica", "Practica")
                        .WithMany()
                        .HasForeignKey("PracticaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_calificaciones_instructor_practica");

                    b.Navigation("Practica");
                });

            modelBuilder.Entity("Practikap.Domain.Entities.Configuracion", b =>
                {
                    b.HasOne("Practikap.Domain.Entities.Usuario", "Actualizador")
                        .WithMany()
                        .HasForeignKey("ActualizadoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_configuracion_actualizador");

                    b.Navigation("Actualizador");
                });

            modelBuilder.Entity("Practikap.Domain.Entities.Ficha", b =>
                {
                    b.HasOne("Practikap.Domain.Entities.Programa", "Programa")
                        .WithMany("Fichas")
                        .HasForeignKey("ProgramaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_fichas_programa");

                    b.Navigation("Programa");
                });

            modelBuilder.Entity("Practikap.Domain.Entities.Mensaje", b =>
                {
                    b.HasOne("Practikap.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("EmisorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_mensajes_emisor");

                    b.HasOne("Practikap.Domain.Entities.Practica", "Practica")
                        .WithMany()
                        .HasForeignKey("PracticaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_mensajes_practica");

                    b.HasOne("Practikap.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("ReceptorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_mensajes_receptor");

                    b.Navigation("Practica");
                });

            modelBuilder.Entity("Practikap.Domain.Entities.Notificacion", b =>
                {
                    b.HasOne("Practikap.Domain.Entities.Regla", "Regla")
                        .WithMany()
                        .HasForeignKey("ReglaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_notificaciones_regla");

                    b.HasOne("Practikap.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notificaciones_usuario");

                    b.Navigation("Regla");
                });

            modelBuilder.Entity("Practikap.Domain.Entities.Observacion", b =>
                {
                    b.HasOne("Practikap.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("AnuladoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_observaciones_anulador");

                    b.HasOne("Practikap.Domain.Entities.Seguimiento", "Seguimiento")
                        .WithMany("Observaciones")
                        .HasForeignKey("SeguimientoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_observaciones_seguimiento");

                    b.Navigation("Seguimiento");
                });

            modelBuilder.Entity("Practikap.Domain.Entities.Practica", b =>
                {
                    b.HasOne("Practikap.Domain.Entities.Usuario", "Aprendiz")
                        .WithMany()
                        .HasForeignKey("AprendizId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_practicas_aprendiz");

                    b.HasOne("Practikap.Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_practicas_empresa");

                    b.HasOne("Practikap.Domain.Entities.Ficha", "Ficha")
                        .WithMany()
                        .HasForeignKey("FichaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_practicas_ficha");

                    b.HasOne("Practikap.Domain.Entities.Usuario", "Instructor")
                        .WithMany()
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_practicas_instructor");

                    b.Navigation("Aprendiz");

                    b.Navigation("Empresa");

                    b.Navigation("Ficha");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("Practikap.Domain.Entities.RegistroAuditoria", b =>
                {
                    b.HasOne("Practikap.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_auditoria_usuario");
                });

            modelBuilder.Entity("Practikap.Domain.Entities.Regla", b =>
                {
                    b.HasOne("Practikap.Domain.Entities.Usuario", "Creador")
                        .WithMany()
                        .HasForeignKey("CreadoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reglas_creador");

                    b.Navigation("Creador");
                });

            modelBuilder.Entity("Practikap.Domain.Entities.Reporte", b =>
                {
                    b.HasOne("Practikap.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("GeneradoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reportes_generador");
                });

            modelBuilder.Entity("Practikap.Domain.Entities.Seguimiento", b =>
                {
                    b.HasOne("Practikap.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("AnuladoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_seguimientos_anulador");

                    b.HasOne("Practikap.Domain.Entities.Practica", "Practica")
                        .WithMany("Seguimientos")
                        .HasForeignKey("PracticaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_seguimientos_practica");

                    b.Navigation("Practica");
                });

            modelBuilder.Entity("Practikap.Domain.Entities.TokenRevocado", b =>
                {
                    b.HasOne("Practikap.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tokens_revocados_usuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Practikap.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("Practikap.Domain.Entities.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_usuarios_rol");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("reporte_practica", b =>
                {
                    b.HasOne("Practikap.Domain.Entities.Practica", null)
                        .WithMany()
                        .HasForeignKey("practica_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reporte_practica_practica");

                    b.HasOne("Practikap.Domain.Entities.Reporte", null)
                        .WithMany()
                        .HasForeignKey("reporte_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reporte_practica_reporte");
                });

            modelBuilder.Entity("Practikap.Domain.Entities.Practica", b =>
                {
                    b.Navigation("Seguimientos");
                });

            modelBuilder.Entity("Practikap.Domain.Entities.Programa", b =>
                {
                    b.Navigation("Fichas");
                });

            modelBuilder.Entity("Practikap.Domain.Entities.Seguimiento", b =>
                {
                    b.Navigation("Observaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
